# Generated by Django 2.0.13 on 2023-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominios_BD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dominio', models.CharField(max_length=256, unique=True)),
                ('id_admin', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_BD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=6)),
                ('flag', models.CharField(default='U', max_length=1)),
            ],
        ),
    ]
