# Generated by Django 2.0.13 on 2023-12-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dominios_bd',
            name='dominio',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='dominios_bd',
            name='id_admin',
            field=models.CharField(max_length=255),
        ),
    ]
