# Generated by Django 2.0.13 on 2023-12-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosting', '0003_auto_20231222_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_bd',
            name='id_admin',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
