# Generated by Django 2.0.13 on 2023-12-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosting', '0004_usuario_bd_id_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_bd',
            name='id_admin',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
