# Generated by Django 2.0.13 on 2023-12-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario_BD',
            fields=[
                ('id_user', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=6)),
                ('flag', models.CharField(max_length=1)),
            ],
        ),
    ]
