# Generated by Django 2.0.13 on 2023-12-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosting', '0002_usuario_bd_senhavoip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_bd',
            name='flag',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
