# Generated by Django 2.0.13 on 2023-12-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosting', '0003_auto_20231216_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_bd',
            name='senhavoip',
            field=models.CharField(max_length=5),
        ),
    ]
