# Generated by Django 2.0.13 on 2023-12-16 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphosting', '0005_auto_20231216_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominios_BD',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dominio', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
